baseURL = 'http://example.org/'
defaultContentLanguage = 'en'
theme = 'anatole'

[params]
title = "I'm Ruikang Tao"
author = "Ruikang Tao"
description = """
Full-stack Engineer
Developing Expertise in Cloud & Network Infra
"""
profilePicture = "images/profile.jpg"

gtagId = "G-W287YYPD0G"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ruikang-tao/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/Rico00121"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:rico00121@outlook.com"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = "https://rico00121.github.io/blog/post/index.xml"

[languages]
[languages.en]
title = "Rico's blog"
weight = 1
languageName = "English"
contentDir = 'content/en'

[languages.en.menus]
[[languages.en.menus.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"
[[languages.en.menus.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"
[[languages.en.menus.main]]
name = "About"
weight = 300
identifier = "about"
url = "https://ricotao.me/"



[languages.cn]
title = "瑞康的博客"
description = "成长路上的碎碎念"
weight = 2
languageName = "Chinese"
contentDir = 'content/cn'

[languages.cn.menus]
[[languages.cn.menus.main]]
name = "主页"
identifier = "home"
weight = 100
url = "/cn"
[[languages.cn.menus.main]]
name = "博客"
weight = 200
identifier = "posts"
url = "/cn/post/"
[[languages.cn.menus.main]]
name = "关于我"
weight = 300
identifier = "about"
url = "https://ricotao.me/"